### ISSUE TITLE
Failure to connect to a broker does not throw a q error

### ISSUE THREAD

**Issue by cmccarthy1** [KxSystems/kafka#32]
**Internally raised issue**

**Describe the bug**
If the q process fails to connect to an invalid kafka broker does not throw a q error but prints out kafka errors and returns the client id that would have been used. This is invalid behaviour.

**To Reproduce**
Run the following in a valid q session initialised with `q kfk.q`

```
q).kfk.Consumer[`metadata.broker.list`group.id!`foobar`0]
```
 
**Expected behavior**
Evaluation of the above should error out with an appropriate error indicating that failure was unsuccessful.

**Screenshots**
There are no relevant screenshots necessary for this

**Desktop (please complete the following information):**
This issue is os independent and a result of implementation decisions

**Additional context**
There is no additional context for this issue necessary

**Comment by cmccarthy1** [comment]
Flagging of this issue doesn't appear to be manageable within the C `kfkClient` function that back ends the `.kfk.Consumer` function. Errors are being seen through `.kfk.errcb` which may get called if an error occurs in a call to `rd_kafka_poll`, this occurs after the creation of the consumer so can't be directly managed.

This behaviour appears to be expected within the librdkafka C api, errors are generally not treated as fatal as they may be transient to the setup rather than permanent (all brokers are down because I'm having network issues, I can't resolve a host because the docker ima), a good discussion on this is available [here](https://github.com/edenhill/librdkafka/issues/64).

One issue with handling errors within the `.kfk.errcb` function (for example the invocation of `.kfk.ClientDel[cid]`) is that within our polling functionality  `rd_kafka_poll` is not the last function invoked with requires the clientid, as such this can lead to segfaults.

More research needed into this but I don't think it can be fixed at the level of `.kfk.Client`

**Comment by mshimizu-kx** [comment]
This was fixed in v2.0
```
q).kafka.newConsumer[`metadata.broker.list`group.id!`foobar`0]
1i
"(1i;-193i;\"foobar:9092/bootstrap: Failed to resolve 'foobar:9092': Name or ..
"(1i;-187i;\"1/1 brokers are down\")"
```

**Comment by cmccarthy1** [comment]
I don't think the code block you're showing there rectifies the defined issue, the behaviour is still the same as before namely that the consumer does still get created and occupies the id `1i` even though it had not been generated in a way that it is callable. Fully rectifying this issue would require that the invocation of the `.kafka.newConsumer` errored rather than returning `1i` indicating that generation of a new consumer was successful

**Comment by mshimizu-kx** [comment]
This operation is successful from the application point of view following the rdkafka specification "The Kafka handle on success or NULL on error (see errstr)". The transferring error is not catchable.

**Comment by mshimizu-kx** [comment]
Timeout was introduced.
```
q)kfk_cfg:(!) . flip(
    (`metadata.broker.list;`localhost:9092);
    (`group.id;`0);
    (`fetch.wait.max.ms;`10);
    (`statistics.interval.ms;`10000);
    (`enable.auto.commit; `false)
    );
q)
q)consumer:.kafka.newConsumer[kfk_cfg; 5000];
'Local: Broker transport failure
  [2]  /home/mshimizu/q/kafka_client.q:173: .kafka.newClient:
  if[(not `group.id in key config) and client_type="c"; '"consumer must define 'group.id' within the config"];
  client:.kafka.newClient_impl[client_type; config; timeout];
         ^
  .kafka.CLIENT_TYPE_MAP,: enlist[client]!enlist[`$client_type];
q))\
q)consumer:.kafka.newConsumer[kfk_cfg; 5000];
'Local: Broker transport failure
  [2]  /home/mshimizu/q/kafka_client.q:173: .kafka.newClient:
  if[(not `group.id in key config) and client_type="c"; '"consumer must define 'group.id' within the config"];
  client:.kafka.newClient_impl[client_type; config; timeout];
         ^
  .kafka.CLIENT_TYPE_MAP,: enlist[client]!enlist[`$client_type];
q))\
q)// Start kafka broker
q)consumer:.kafka.newConsumer[kfk_cfg; 5000];
```
